Homework 2
petrovromanval/frontend_homework pull request #2
Opened 2020-03-07 15:19 UTC by petrovromanval

2020-03-08 08:13 UTC, AlexMubarakshin requested changes
Оставил пару комментов в html'ке по типам input'ов.
Необходимо их исправить 😊

2020-03-08 08:13 UTC, AlexMubarakshin commented on homework_2/FenderStratocaster.html
> +                    Ваше E-mail<br><input type="text" placeholder="Введите ваш E-mail">
Используй для ввода email, input с типом 'email'

2020-03-08 08:13 UTC, AlexMubarakshin commented on homework_2/FenderStratocaster.html
> +                    Контактный телефон<br><input type="text" placeholder="+7 XXX XXXXXXX">
Аналогично как и с email

2020-03-08 08:13 UTC, AlexMubarakshin commented on homework_2/FenderStratocaster.html
> +            <input type="button" value="Кнопка">
"Кнопка"? 🧐😀

2020-03-08 17:16 UTC, petrovromanval commented on homework_2/FenderStratocaster.html
> +                    Ваше E-mail<br><input type="text" placeholder="Введите ваш E-mail">
Исправил

2020-03-08 17:16 UTC, petrovromanval commented on homework_2/FenderStratocaster.html
> +                    Контактный телефон<br><input type="text" placeholder="+7 XXX XXXXXXX">
Исправил

2020-03-08 17:22 UTC, petrovromanval commented on homework_2/FenderStratocaster.html
> +            <input type="button" value="Кнопка">
Просто она пока ни к какому действию не привязана, во я ее и назвал просто "Кнопка"))).  Сделал ее, потому что в ДЗ было написано использовать тег button. Я ее удалю)

2020-03-09 08:39 UTC, AlexMubarakshin commented on homework_2/FenderStratocaster.html
>              <input type="reset" value="Очистить">
Про тег button имелось что его можно (И даже необходимо) использовать вместо:
```html
<input type="submit" value="Отправить">
```

вот это:
```html
<button type="submit">Отправить</button>
```

😊

2020-03-09 15:22 UTC, petrovromanval commented on homework_2/FenderStratocaster.html
>              <input type="reset" value="Очистить">
Спасибо, что поправил, а то я чет вместо тега <button> использовал type="button" в input. Исправил и сделал commit №6

2020-03-10 12:11 UTC, merged